### ISSUE TITLE
Incompatible with [JECh]Just Enough Characters.

### ISSUE THREAD

**Issue by wasdspace** [CleanroomMC/HadEnoughItems#1]
[https://www.mcmod.cn/class/840.html](url)
[https://www.curseforge.com/minecraft/mc-mods/just-enough-characters](url)
Forgive me for not knowing exactly who's fault it is, but the original JEI didn't have this problem, so I'm reporting it here.
Thanks for your work!

**Comment by Rongmario** [comment]
Any crash reports or logs?

**Comment by wasdspace** [comment]
I'm sorry I wasn't clear. JECh is a mod that allows Chinese players use pinyin(Chinese spelling style), but it doesn't work with your mod, no crash.

**Comment by Rongmario** [comment]
I'm not going to support JeCH unfortunately. If JeCh's devs or someone has time, they can explicitly support HEI because there are too many things I change pertaining search trees.
