### ISSUE TITLE
Broken Thermal textures

### ISSUE THREAD

**Issue by MasterEnderman** [CleanroomMC/HadEnoughItems#13]
When switching from JEI to HEI all machines from thermal expansion render as black/pink boxes.

**Comment by Rongmario** [comment]
This sounds more like a LoliASM issue, in which, restarting should fix it.

**Comment by MasterEnderman** [comment]
Guess I have to check that again. Why does it break the textures on the first start?

**Comment by Rongmario** [comment]
Because of very awful hacks to decrease memory usages, one day I'll get around to making it work on first launch.
