### ISSUE TITLE
HEI only showing one guidebook when there are multiple

### ISSUE THREAD

**Issue by xemnes** [CleanroomMC/HadEnoughItems#17]
unsure if this covers guidebooks added by mods, but i have 3 different guidebooks i have made in patchouli but only one of them shows up in HEI. when using JEI, this doesnt happen.

![image](https://user-images.githubusercontent.com/603338/169203173-309670bb-c350-4829-9c34-63b02ed46fe1.png)

**Comment by Caedis** [comment]
Do the books show up when you search their respective mods?

**Comment by xemnes** [comment]
the books ive used as an example were made myself using patchouli and werent added from another mod. but im unsure if guidebooks from other mods show up or not. id say yes if the guidebooks item is registered by the mod and not patchouli.
