### ISSUE TITLE
require_prefix option not working

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#2]
After replaced JEI -> HEI i found that `require_prefix` config option not working anymore.

This is my config:
![HEI config window](https://i.imgur.com/tVQYWeK.png)

And there is search, clearly including all items with "Nutrients" word in tooltip. Before update this would be seen only with `#Nutrients` search:
![HEI show tooltips](https://i.imgur.com/M0Dp7Vw.png)

Im not sure, but seems like using `B:ultraLowMemoryUsage=true` fix this to normal behaviour. Through, i cant use this option because game freezes too hard with it.

**Comment by Rongmario** [comment]
I'm getting the exact opposite behaviour, very weird

**Comment by Krutoy242** [comment]
Still looking for solution!

Should i provide additional information?

**Comment by Rongmario** [comment]
I'll try fix this in time for the next build
