### ISSUE TITLE
[New Feature]Cheat only mode (like TMI) for map builders and server ops

### ISSUE THREAD

**Issue by HowardZHY** [CleanroomMC/HadEnoughItems#22]
Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by htmlcsjs** [comment]
:raised_eyebrow: isnt that implemented already

**Comment by HowardZHY** [comment]
> 🤨 isnt that implemented already

of course not

**Comment by htmlcsjs** [comment]
![image](https://user-images.githubusercontent.com/46023024/171677892-804815f4-4073-40b5-afee-8265032536e9.png)
(dont mind it saying jei, either my ver is old or rong needs to update the lang)

**Comment by Rongmario** [comment]
You have an old version, and also, we already have cheat mode; don't quite understand.

**Comment by HowardZHY** [comment]
Now I use cheat mode + infinity item editor.

why don't add some useful commands from NEI/TMI like quick gamemode change

**Comment by htmlcsjs** [comment]
![image](https://user-images.githubusercontent.com/46023024/171703405-ca43fa4c-1e5e-418a-a957-e286e0374513.png)

**Comment by xemnes** [comment]
such a thing already exists anyway, https://www.curseforge.com/minecraft/mc-mods/just-enough-buttons

https://www.curseforge.com/minecraft/mc-mods/ftb-utilities-forge

**Comment by HowardZHY** [comment]
let me check it
