### ISSUE TITLE
bufferIngredientRenders conflicts with OptiFine's Fast Render

### ISSUE THREAD

**Issue by HowardZHY** [CleanroomMC/HadEnoughItems#24]
![image](https://user-images.githubusercontent.com/96782166/172059357-dcdcacde-3157-4f71-8fa3-8b4051907266.png)

**Comment by Rongmario** [comment]
Try turning `bufferIngredientRenders` off in the configs.

**Comment by HowardZHY** [comment]
works. could pin this
