### ISSUE TITLE
Some things that can be found with JEI, but HEI can't find them

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/HadEnoughItems#25]
有些可以用JEI搜到的东西HEI搜不到
(配置都是一样的(全开))
例子:
(Same configuration)
example:
JEI:
![JEI](https://user-images.githubusercontent.com/47917763/173506247-b2ec20a3-75bc-47ed-95dc-75e876df7613.png)

HEI:
![HEI](https://user-images.githubusercontent.com/47917763/173506432-5bf02fef-3719-4f23-a985-43a30a7b1005.png)

**Comment by Xelbayria** [comment]
I was going to report this issue. I had the same issue with HEI. 
I used **@tfc ore** in HEI and it should have bought up the ore stones from TFC (terrafirmacraft)... well I'll let the picture speak for itself

![_map](https://user-images.githubusercontent.com/12866666/173997082-c965c68a-6fe9-4c36-8643-a13e96cce874.png)

as you can see that there are no ores!!! in the HEI. * sigh *

**Comment by magcicada** [comment]
@Xelbayria I think you need type '@tfcore' to search it.

**Comment by magcicada** [comment]
the modid search can not work with ' '

**Comment by Romz24** [comment]
I also encountered this problem too when using the [RLArtifacts](https://www.curseforge.com/minecraft/mc-mods/rl-artifacts) mod. When I write **@artifacts** or **@RLArtifact** in the search, I get an incomplete list of items (this can be understood from the list of items from the creative).

![image](https://i.imgur.com/XaYtCYv.png)
![image](https://i.imgur.com/JyxqJ88.png)

**Comment by Rongmario** [comment]
Closing from no feedback, feel free to open a new issue.
