### ISSUE TITLE
Mods cannot hide items in HEI

### ISSUE THREAD

**Issue by freopt** [CleanroomMC/HadEnoughItems#31]
For example, Chisels and Bits, Facades, Flat Colored Blocks.
CraftTweaker hiding _does_ work, however

**Comment by X-Niter** [comment]
Regarding CraftTweaker - 
I did 
```
mods.jei.JEI.hide(<appliedenergistics2:facade>);
```
And when loading with HEI nothing happened, but with loading JEI the facades went away as they should. 

I actually had to turn on HEI hide mode and then just set them to be hiden and make sure I ship the hidden config.

**Comment by Rongmario** [comment]
Only the config method works then?

**Comment by X-Niter** [comment]
Just ran another test here. 
Vanilla is good, another two random mods are working, then I add ae2 and the items from that mod don't go away.. 

I can continue this by adding Chisel and flat colored blocks to see what happens.

**Comment by X-Niter** [comment]
freopt is correct, it is indeed an odd little bug, tested on my end. And craft tweaker does not work for everything, AE2 and multiple shades of flat colored blocks being an example.

It would seems that multiple items with the same "Modid:ItemId" do not get listened too for some reason.

**Comment by Rongmario** [comment]
Closing from no feedback, feel free to open a new issue.
