### ISSUE TITLE
Cannot hide specific items

### ISSUE THREAD

**Issue by kaanyalova** [CleanroomMC/HadEnoughItems#35]
When trying to hide some items such as `water_tank`s from agricraft or `gen_sample`s
from gendustry hiding one of the items hides all of the items with same item id with no way of unhiding specific items.

I can hide a single `appliedenergistics2:facade` but i can't do the same with `agricraft:water_tank`

Forge version: 14.23.5.2860
HadEnoughItems version: 4.24.0
Agricraft version: 2.12.0-1.12.2-b2
Forestry version: 5.8.2.422
AppliedEnergistics2 version: rv6-stable-7-extended_life-v0.53.7

**Comment by kaanyalova** [comment]
Trying to hide all but one item using crafttweaker doesn't work either

```zs
mods.jei.JEI.hide(<agricraft:water_tank>);
mods.jei.JEI.addItem(<agricraft:water_tank>.withTag({agri_material_meta: 0, agri_material: "minecraft:planks"}));
```

It removes the items from HEI but it doesn't add back the item 
  
removing some items like `appliedenergistics2:facade`s  using crafttweaker doesn't work either similar to #31 
```zs
mods.jei.JEI.hide(<appliedenergistics2:facade>);
```

**Comment by Gandalf360one** [comment]
Same problem at my side

**Comment by Rongmario** [comment]
Closing from no feedback, feel free to open a new issue.
