### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kasia1403** [CleanroomMC/HadEnoughItems#37]
When crafting multiple quantity of one item at once HEI causes so huge lag that it freezes Minecraft. Changing HEI to JEI fixes it, but Minecraft with JEI loads for ages ( at least 2 hours ) while Minecraft with HEI loads 30 minutes.

**Comment by ACGaming** [comment]
At this point, I‘m almost too afraid to ask for your specs. 👀

**Comment by Rongmario** [comment]
No response, closing for now.
