### ISSUE TITLE
HEI与Hidden Armor Mod崩溃

### ISSUE THREAD

**Issue by Lonelyxiya** [CleanroomMC/HadEnoughItems#44]
![WS)%8DVENE25X}9OCG2$N52](https://user-images.githubusercontent.com/83713575/212806391-b1854929-33d5-4dca-83b5-5f2ee024ed23.jpg)
Hidden Armor Mod与HEI冲突 
一打开物品栏就会崩溃
[crash-2023-01-17_11.45.46-client.txt](https://github.com/CleanroomMC/HadEnoughItems/files/10431017/crash-2023-01-17_11.45.46-client.txt)

**Comment by Rongmario** [comment]
關掉 HEI 的 `bufferIngredientRenders`
