### ISSUE TITLE
Suggestion: Add recipe/usage hotkeys for looked-at block

### ISSUE THREAD

**Issue by Xetaxheb** [CleanroomMC/HadEnoughItems#46]
As title, the ability to press (preferably separate bind from existing recipe/usage) to open the HEI recipe/usage gui for block under crosshair in-world.

**Comment by Rongmario** [comment]
[HWYLA](https://www.curseforge.com/minecraft/mc-mods/hwyla) already possesses this ability. By default it is binded with `NUMPAD 3` and `NUMPAD 4`
