### ISSUE TITLE
HEI crashes when using "show recipe" bound to mouse button on pin with "R" marker

### ISSUE THREAD

**Issue by SRabbelier** [CleanroomMC/HadEnoughItems#48]
1. Bind "show recipe" to (mouse) "button 4"
2. Pin an item from the recipe page so that it shows up in HEI with an "R" on it
3. Use "show recipe" on pinned item

Client crashes with `java.lang.ClassCastException: com.github.vfyjxf.jeiutilities.jei.ingredient.RecipeInfo cannot be cast to net.minecraft.item.ItemStack`

https://mclo.gs/UybU6eA

HEI: 4.23.0
Modpack: https://beta.curseforge.com/minecraft/modpacks/nomi-ceu/files/4332402

**Comment by Rongmario** [comment]
Instead of binding that to a mouse button, you can just keep config `mouseClickToSeeRecipes=true`?

**Comment by Rongmario** [comment]
Closing from no feedback, feel free to open a new issue.
