### ISSUE TITLE
The HEI crashes at the end of the minecraft load

### ISSUE THREAD

**Issue by blazenight** [CleanroomMC/HadEnoughItems#49]
When loading minecraft at the end of the download, HEI decided to crash it, what could be the problem?

Crash Report : https://gist.github.com/blazenight/fb8c1f5a62fbbd0d2472dee8bbd16965

This is the first time I'm throwing reports here. That's why I don't really know how to design them.

Help please.

**Comment by Rongmario** [comment]
1. Can I get the full log?
2. Try without liteloader and its mods first and see if it still crashes

**Comment by blazenight** [comment]
The full log is currently being uploaded to google drive since github does not accept large logs of 57 megabytes.
Log: https://drive.google.com/file/d/1NrmJu84NKV3IZXzokd5O983urlE_BIqc/view?usp=share_link

**Comment by blazenight** [comment]
> 1. Могу ли я получить полный журнал?
[latest.log](https://github.com/CleanroomMC/HadEnoughItems/files/10743036/latest.log)
A new log since the one I understood is broken
> 2. Попробуйте сначала без liteloader и его модов и посмотрите, все еще вылетает
I'll try without ModLoader.

**Comment by Bear-Creator** [comment]
I faced the same problem. 
The problem is in other languages such as Russian.
It fixed, when I changed minecraft language form ru_ru to en_us.
Crash log:
[2023-03-22-7.log.gz](https://github.com/CleanroomMC/HadEnoughItems/files/11041852/2023-03-22-7.log.gz)
