### ISSUE TITLE
Forge fluid bucket variants are hidden

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#5]
After one of recent updates, i cant see forge buckets anymore.

I use default settings, and when im looking for `Bucket` in JEI search, i see only hardcoded non-forge buckets:

![JEI tab with buckets](https://i.imgur.com/FccFXGG.png)

I see there is new option in config. I set it to `forge:bucketfilled` but it wont help:

![JEI Options](https://i.imgur.com/jjsWA3G.png)

**Comment by Rongmario** [comment]
Fixed in cb15590
