### ISSUE TITLE
Game not responding when joining world right after pack load with/after 4.24.4 update

### ISSUE THREAD

**Issue by xJon** [CleanroomMC/HadEnoughItems#53]
To reproduce, start Tekkit 2 (version `1.2.1`) and immediately after the pack finishes loading, join an existing world (singleplayer or multiplayer). The client will stop responding indefinitely.
Downgrading HEI to `4.24.3` and under "resolves" the issue.

**Comment by xJon** [comment]
Resolved by https://github.com/CleanroomMC/HadEnoughItems/commit/01912e0d8eb490a0fad23764df1e57b5229dfa51.

**Comment by Pyker** [comment]
More exactly, resolved by https://github.com/CleanroomMC/HadEnoughItems/commit/a293c8bab3aebac08127d161b27d0181b0d36a47
