### ISSUE TITLE
HEI ignore Nbt in removeAndHide

### ISSUE THREAD

**Issue by rogedkone** [CleanroomMC/HadEnoughItems#54]
HEI ignore Nbt when using HEI.removeAndHide
CraftTweaker:
<storagedrawers:basicdrawers:1>.withTag({material: "oak"})
GroovyScript:
item('storagedrawers:basicdrawers', 1).withNbt([material: "oak"])

Remove recipe use <storagedrawers:basicdrawers:1>.withTag({material: "oak"})
And hide recipe icons use <storagedrawers:basicdrawers:1>

![image](https://user-images.githubusercontent.com/85563010/236290606-ec6b06cf-31d8-4068-8d4c-f0429e564262.png)

**Comment by Rongmario** [comment]
This should've been fixed by now, closing it, if the new (4.26.0) version still has this issue please open a new issue.
