### ISSUE TITLE
HEI causes Heavy RAM usage and longer loading time when installed, How to Fix?

### ISSUE THREAD

**Issue by Mysticpasta1** [CleanroomMC/HadEnoughItems#55]
When using HEI without NEI and FEI on 1.12.2 forge, there can be a RAM spike that can go up a few GB to 12GB (12GB when using multiple mods), it can also cause a long loading time when using it will multiple mods that have JEI plugins for them. Is there a way to reduce the RAM usage and loading time when starting the game with the mod.

**Comment by Rongmario** [comment]
It's a JEI issue and HEI already tries to fix and alleviate a lot of the issues. Do you have a list of mods that you're using?

**Comment by Mysticpasta1** [comment]
Yes one minute, there is a lot of them :)

**Comment by ChromaPIE** [comment]
Using E2E-E modpack, yes it's a thing.
