### ISSUE TITLE
Finding recipes for items with NBT output every NBT variant

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#6]
When i press `R` in JEI, i can see recipes for each Forestry bee:
![Different bee recipes](https://i.imgur.com/C3nx1yD.gif)

But when i do same in HEI, i see recipes for every bee:

![Every bee in JEI](https://i.imgur.com/o8EzNpe.gif)

**Comment by freopt** [comment]
can confirm that HEI 4.17+ displays recipes for all nbt variants of an item
happens with extrautils, techreborn, etc.

reverting to 4.16 fixes

**Comment by Rongmario** [comment]
Fixed in cb15590
