### ISSUE TITLE
TippedArrowRecipeMaker does not check if the recipe exists, it always shows the recipe

### ISSUE THREAD

**Issue by Atricos** [CleanroomMC/HadEnoughItems#62]
### Steps to Reproduce the Bug

1. Add HEI and CraftTweaker to your modpack.
2. Remove the Tipped Arrow recipe with CraftTweaker, for example: `recipes.removeAll();` or `recipes.remove(<minecraft:tipped_arrow>);` or `recipes.removeByInput(<minecraft:arrow>);`.
3. Launch the game.
4. Click on any Tipped Arrow: HEI still shows the recipe (seen below), even though their crafting recipes don't work (also see below).

### Expected Behavior

HEI shouldn't show the recipe, since it does not exist anymore.

HEI doesn't actually check if the recipe exists:
![image](https://github.com/mezz/JustEnoughItems/assets/24854267/15e9d11e-50a1-4172-bd18-8593a82d7f4b)

I think this is probably fixable by just adding an if clause:
`if (recipeExists) {addRecipe();}` instead of just `addRecipe();`

### Actual Behavior

HEI still shows the recipe:
![image](https://github.com/mezz/JustEnoughItems/assets/24854267/cbb5ca98-36bc-45b0-884f-4b26f3fdeb98)

Even though the recipe doesn't work:
![image](https://github.com/mezz/JustEnoughItems/assets/24854267/e073f146-0229-467e-95c6-ded22e9c0b68)

## Version

I am using HadEnoughItems_1.12.2-4.25.0

**Comment by Primitive-Human** [comment]
Not JEI/HEI's fault.

https://github.com/CraftTweaker/CraftTweaker/issues/844#issuecomment-529169532

**Comment by Atricos** [comment]
> Not JEI/HEI's fault.
> 
> [CraftTweaker/CraftTweaker#844 (comment)](https://github.com/CraftTweaker/CraftTweaker/issues/844#issuecomment-529169532)

Let me reiterate: CraftTweaker removes the recipes perfectly, they cannot be crafted anymore, _however they're still shown in JEI/HEI_.

Moreover, looking at the quoted code segment, this is most likely JEI's/HEI's fault, as **it does not check if the recipe exists, it adds the recipe regardless**.

So I think the issue is most likely fixable by adding a clause like:
`if (recipeExists) {addRecipe();}` instead of just `addRecipe();`

**Comment by KorewaLidesu** [comment]
There is no way to ensure if the recipe exist since HEI cache recipe early before CT effectively removing it.
If you want to do it, instead trigger the recipe remove early before HEI start caching recipe.

**Comment by Rongmario** [comment]
Use `GroovyScript` as recipe removal is sufficiently covered by it and reloads properly.
