### ISSUE TITLE
[Feature Request] add `hei_bookmarks.ini` reload

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#63]
During developing its always nice to use Bookmarks to copy item tags, especially `ForgeCaps` that CraftTweaker unable to copy easy way.

But, sometimes i need to give myself specified item
- I cant grant myself items with long nbt (10k symbols, e.g. Tcon tool / backpack)
- I cant give myself items with `ForgeCaps`

Best solution so far for me is 
1. add new line to `hei_bookmarks.ini`
2. reload game

It would be nice to have command `/hei_bookmarks_reload` or smth to reload all bookmarks from file **without need to reload game**.

**Comment by Rongmario** [comment]
The reloading is broken right now, I'm going to address this in 4.26.0

**Comment by Krutoy242** [comment]
Tested - working fine!
