### ISSUE TITLE
[Request] Recipe Exporter

### ISSUE THREAD

**Issue by Darkaken** [CleanroomMC/HadEnoughItems#69]
Hey there!
I would like if its possible to export all recipes (included modded ones) to a file. Im currently playing a lot of GregTech so it would be quite useful to me, as I could use that data to automatically make recipe trees and flowcharts. Thanks in advance!

**Comment by WaitingIdly** [comment]
You might find this helpful: https://github.com/friendlyhj/JEIExporter

**Comment by Darkaken** [comment]
I installed the exporter but my game kept crashing, so I tried using that on a fresh vanilla instance (with JEI) and it crashed for the same reason. It seems it uses deprecated JEI funcionality. Thanks though!

**Comment by Krutoy242** [comment]
> I installed the exporter but my game kept crashing, so I tried using that on a fresh vanilla instance (with JEI) and it crashed for the same reason. It seems it uses deprecated JEI funcionality. Thanks though!

I tested [friendlyhj/JEIExporter](https://github.com/friendlyhj/JEIExporter) with my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended) and its working fine. I exported all recipes and made this chart:
https://github.com/Krutoy242/mc-craft-tree

So, you just need to fix your crash.

**Comment by Darkaken** [comment]
> > I installed the exporter but my game kept crashing, so I tried using that on a fresh vanilla instance (with JEI) and it crashed for the same reason. It seems it uses deprecated JEI funcionality. Thanks though!
> 
> I tested [friendlyhj/JEIExporter](https://github.com/friendlyhj/JEIExporter) with my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended) and its working fine. I exported all recipes and made this chart: https://github.com/Krutoy242/mc-craft-tree
> 
> So, you just need to fix your crash.

Thats great, loved your visualizer! Do you mind sharing your JEI.jar file? Im building my modpack on courseforge and perhaps thats the problem. I made a groovyscript parser for the recipes, but many files require manual work so its tiresome.

**Comment by Krutoy242** [comment]
> > > I installed the exporter but my game kept crashing, so I tried using that on a fresh vanilla instance (with JEI) and it crashed for the same reason. It seems it uses deprecated JEI funcionality. Thanks though!
> > 
> > 
> > I tested [friendlyhj/JEIExporter](https://github.com/friendlyhj/JEIExporter) with my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended) and its working fine. I exported all recipes and made this chart: [Krutoy242/mc-craft-tree](https://github.com/Krutoy242/mc-craft-tree)
> > So, you just need to fix your crash.
> 
> Thats great, loved your visualizer! Do you mind sharing your JEI.jar file? Im building my modpack on courseforge and perhaps thats the problem. I made a groovyscript parser for the recipes, but many files require manual work so its tiresome.

This is my HEI.jar file https://www.curseforge.com/minecraft/mc-mods/had-enough-items/files/4810661

**Comment by Darkaken** [comment]
> > > > I installed the exporter but my game kept crashing, so I tried using that on a fresh vanilla instance (with JEI) and it crashed for the same reason. It seems it uses deprecated JEI funcionality. Thanks though!
> > > 
> > > 
> > > I tested [friendlyhj/JEIExporter](https://github.com/friendlyhj/JEIExporter) with my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended) and its working fine. I exported all recipes and made this chart: [Krutoy242/mc-craft-tree](https://github.com/Krutoy242/mc-craft-tree)
> > > So, you just need to fix your crash.
> > 
> > 
> > Thats great, loved your visualizer! Do you mind sharing your JEI.jar file? Im building my modpack on courseforge and perhaps thats the problem. I made a groovyscript parser for the recipes, but many files require manual work so its tiresome.
> 
> This is my HEI.jar file https://www.curseforge.com/minecraft/mc-mods/had-enough-items/files/4810661

Thanks! Somehow that fixed my error. How long did it take to export your recipes? Im running the program for around an hour by now on 2 computers.

**Comment by Krutoy242** [comment]
> Thanks! Somehow that fixed my error. How long did it take to export your recipes? Im running the program for around an hour by now on 2 computers.

This is not proper place to discuss it.
