### ISSUE TITLE
在cleanroom上使用HEI有概率导致崩溃

### ISSUE THREAD

**Issue by PathdarX** [CleanroomMC/HadEnoughItems#75]
在cleanroom上使用HEI时，打开合成配方后最小化游戏窗口，再重新打开游戏窗口有概率导致客户端崩溃
https://mclo.gs/7GMuV1R
上面是崩溃日志
经过测试就算在只有HEI的情况下也会导致崩溃

**Comment by skrjii** [comment]
[RecipesGui.zip](https://github.com/user-attachments/files/15838716/RecipesGui.zip)

**Comment by kappa-maintainer** [comment]
请使用最新fugue，不过这并非真正解决了这个问题，只是把小于0的值改成0而已
