### ISSUE TITLE
Hiding items with CraftTweaker doesn't work

### ISSUE THREAD

**Issue by freopt** [CleanroomMC/HadEnoughItems#8]
Using ```mods.jei.JEI.removeAndHide(<extendedcrafting:crafting_table>)``` gives 
```[AVAILABLE][CLIENT][INFO] Hiding item in JEI: <extendedcrafting:crafting_table> ``` 
in crafttweaker.log but it still shows up in JEI

HEI 4.20.1

**Comment by Rongmario** [comment]
I'm unable to successfully replicate this, can you zip your minecraft instance and send it my way? I'm able to remove vanilla or modded items just fine with `mods.jei.JEI.removeAndHide`, may I know which version of CraftTweaker you're using?

**Comment by freopt** [comment]
https://www.mediafire.com/file/gvbppbovzvmr9zt/a.zip/file
theres a list of disabled items in constants.zs that uses removeAndHide

**Comment by Rongmario** [comment]
Thanks, someone else over on our discord also directed me to a modpack and I can confirm that this bug does happen in certain contexts. Next update will fix this.
